In [1]:
import os
import cv2
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from sklearn.model_selection import train_test_split
from keras.models import load_model

In [7]:
# Set the path to your labeled dataset folders
malicious_dir = 'QR codes\Malicious\malicious'
non_malicious_dir = r'QR codes\Benign\benign'

In [8]:
os.listdir(non_malicious_dir)

['benign_0.png',
 'benign_1.png',
 'benign_10.png',
 'benign_100.png',
 'benign_1000.png',
 'benign_10000.png',
 'benign_10001.png',
 'benign_10002.png',
 'benign_10003.png',
 'benign_10004.png',
 'benign_10005.png',
 'benign_10006.png',
 'benign_10007.png',
 'benign_10008.png',
 'benign_10009.png',
 'benign_1001.png',
 'benign_10010.png',
 'benign_10011.png',
 'benign_10012.png',
 'benign_10013.png',
 'benign_10014.png',
 'benign_10015.png',
 'benign_10016.png',
 'benign_10017.png',
 'benign_10018.png',
 'benign_10019.png',
 'benign_1002.png',
 'benign_10020.png',
 'benign_10021.png',
 'benign_10022.png',
 'benign_10023.png',
 'benign_10024.png',
 'benign_10025.png',
 'benign_10026.png',
 'benign_10027.png',
 'benign_10028.png',
 'benign_10029.png',
 'benign_1003.png',
 'benign_10030.png',
 'benign_10031.png',
 'benign_10032.png',
 'benign_10033.png',
 'benign_10034.png',
 'benign_10035.png',
 'benign_10036.png',
 'benign_10037.png',
 'benign_10038.png',
 'benign_10039.png',
 'benign_

In [54]:
# List to store the labels ('malicious' or 'non-malicious') and images
labels = []
images = []

In [55]:
# Load malicious images
for filename in os.listdir(malicious_dir):
    if filename.endswith(".png") or filename.endswith(".jpg"):
        labels.append('malicious')
        img = cv2.imread(os.path.join(malicious_dir, filename))
        img = cv2.resize(img, (128, 128))
        images.append(img)

In [56]:
# Load non-malicious images
for filename in os.listdir(non_malicious_dir):
    if filename.endswith(".png") or filename.endswith(".jpg"):
        labels.append('non-malicious')
        img = cv2.imread(os.path.join(non_malicious_dir, filename))
        img = cv2.resize(img, (128, 128))
        images.append(img)

In [57]:
# Convert labels to numerical values
labels = np.array([1 if label == 'malicious' else 0 for label in labels])
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

In [58]:
# Normalize the image data
X_train = np.array(X_train) / 255.0
X_test = np.array(X_test) / 255.0

In [59]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))


Epoch 1/10
100/100 [==============================] - 62s 617ms/step - loss: 0.6450 - accuracy: 0.6325 - val_loss: 0.3601 - val_accuracy: 0.8763
Epoch 2/10
100/100 [==============================] - 50s 497ms/step - loss: 0.2408 - accuracy: 0.9075 - val_loss: 0.1411 - val_accuracy: 0.9588
Epoch 3/10
100/100 [==============================] - 52s 524ms/step - loss: 0.0844 - accuracy: 0.9678 - val_loss: 0.0493 - val_accuracy: 0.9837
Epoch 4/10
100/100 [==============================] - 50s 505ms/step - loss: 0.0282 - accuracy: 0.9928 - val_loss: 0.0473 - val_accuracy: 0.9825
Epoch 5/10
100/100 [==============================] - 47s 472ms/step - loss: 0.0094 - accuracy: 0.9984 - val_loss: 0.0485 - val_accuracy: 0.9775
Epoch 6/10
100/100 [==============================] - 53s 535ms/step - loss: 0.0059 - accuracy: 0.9984 - val_loss: 0.0273 - val_accuracy: 0.9912
Epoch 7/10
100/100 [==============================] - 49s 487ms/step - loss: 0.0025 - accuracy: 0.9997 - val_loss: 0.0121 - val_ac

In [60]:
os.chdir("D:\myProject\QR Detection\Final Project")
model.save('qr_code_CNN_model.h5')


In [ ]:
from sklearn.metrics import recall_score,precision_score,f1_score,confusion_matrix


In [2]:
model = load_model('qr_code_CNN_model.h5')


In [3]:
def classify_qr_code(image_path):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (128, 128))
    image = np.expand_dims(image, axis=0)
    image = image / 255.0

    classes = model.predict(image)

    return classes

In [ ]:
classify_qr_code(r'C:\Users\ACER\OneDrive\Desktop\Final Project\QR codes\Malicious\malicious\malicious_416251.png')

In [66]:
def classify_qr_code(image_path):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (128, 128))
    image = np.expand_dims(image, axis=0)
    image = image / 255.0

    classes = model.predict(image)

    return classes
    
    # Assuming you have two classes: Malicious and Non-Malicious
    if classes[0][0]>=0.6:
        return "Malicious"
    else:
        return "Non-Malicious"


In [ ]:
0.9987

In [119]:
output=model.predict(X_test)

25/25 [==============================] - 4s 151ms/step


In [120]:
y_pred=[]
for i in output:
    if i>=0.6:
        y_pred.append(1)
    else:
        y_pred.append(0)
        

In [128]:
from sklearn.metrics import confusion_matrix,f1_score,precision_recall_curve,accuracy_score,roc_auc_score
confusion_matrix(y_test,y_pred)

array([[377,   1],
       [  0, 422]], dtype=int64)

In [122]:
accuracy_score(y_test,y_pred)

0.99875

In [123]:
f1_score(y_test,y_pred)

0.9988165680473373

In [124]:
precision_recall_curve(y_test,y_pred)

(array([0.5275    , 0.99763593, 1.        ]),
 array([1., 1., 0.]),
 array([0, 1]))

In [127]:
roc_auc_score(y_test,y_pred)

0.9986772486772486